config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  
  root "home#index"
  
  devise_for :users, path_prefix: :auth
    
  resources :apps
  resources :users
  
  match '/store-unavailable' => 'home#store_off', :via => :get, as: :store_off
end

app/views/apps/_app.html.haml
.details-shade
  .col-md-6.details-left
    =image_tag app.avatar(:thumb), {class: "img-circle border-effect", alt: app.name}
  .col-md-6.details-right
    %h3=app.name
    %h4 Imprescindibles
    .clearfix
    %p=app.short_description
    %a.app-read-more{:href => app_path(app)}
      Read more
      %i.fa.fa-chevron-right
    -if current_user and current_user.is_admin?
      %a.app-edit{:href => edit_app_path(app)}
        Edit
        %i.fa.fa-chevron-right
  .clearfix

app/views/apps/_form.html.haml
= form_for @app, html: {class: "form", multipart: true} do |f|
  - if @app.errors.any?
    #error_explanation
      %h2= "#{pluralize(@app.errors.count, "error")} prohibited this app from being saved:"
      %ul
        - @app.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name
    = f.text_field :name, {class: "form-control"}
  - if @app.app_type == "ios"
    .form-group
      = f.label :app_store
      = f.text_field :app_store, {class: "form-control"}
  -else
    .form-group
      = f.label :google_store
      = f.text_field :google_store, {class: "form-control"}
  .form-group
    = f.label :download_link
    = f.text_field :download_link, {class: "form-control"}
  .form-group
    = f.label :avatar
    = f.file_field :avatar, {class: "form-control"}
  .form-group
    = f.label :background
    = f.file_field :background, {class: "form-control"}
  .form-group
    = f.label :description
    = f.bootsy_area :description, {class: "form-control"}
  .form-group
    = f.label :short_description
    = f.text_area :short_description, {class: "form-control"}
  .actions
    = f.submit 'Save', {class: "btn btn-info btn-block"}

app/views/apps/_new_form.html.haml
= form_for @app, html: {class: "form", multipart: true} do |f|
  - if @app.errors.any?
    #error_explanation
      %h2= "#{pluralize(@app.errors.count, "error")} prohibited this app from being saved:"
      %ul
        - @app.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label "Select Store"
    - kind_collection = [OpenStruct.new({id: "android", name: "Google Store"}), OpenStruct.new({id: "ios", name: "App Store"})]
    = f.collection_select(:app_type, kind_collection, :id, :name, {}, {class: "form-control"})
  .form-group.appstore
    = f.label :app_store
    = f.text_field :app_store, {class: "form-control"}
  .form-group.googlestore
    = f.label :google_store
    = f.text_field :google_store, {class: "form-control"}
  .form-group
    = f.label "Featured"
    - kind_collection = [OpenStruct.new({id: true, name: "Featured"}), OpenStruct.new({id: false, name: "Not Featured"})]
    = f.collection_select(:featured, kind_collection, :id, :name, {}, {class: "form-control"})
  .actions
    = f.submit 'Save', {class: "btn btn-info btn-block"}
:javascript
  $(document).ready(function(){
    var disable_or_enable = function(select){
      var kind = $(select).val()

      if(kind == "ios"){
        $("form").find(".appstore").removeClass("hidden")
        $("form").find(".googlestore").addClass("hidden")
      }else{
        $("form").find(".appstore").addClass("hidden")
        $("form").find(".googlestore").removeClass("hidden")
      }
    };

    $("select[name*='[app_type]']").change(function(ev){
      disable_or_enable(this)
    });

    $("select[name*='[app_type]']").trigger("change");
  })

app/views/apps/edit.html.haml
#admin-view
  .headding-notify
    .headding-left
      = link_to apps_path do
        %h5.pro-link
          %i.fa.fa-chevron-left
    .headding-mid
      %h5.pro-link Editando App
    .headding-right
      = link_to @app do
        %h5.pro-link
          %i.fa.fa-eye
    .clearfix
  .shade
    .container
      .col-md-12.col-sm-12
        = render 'form'
        %hr/
        %a.btn.btn-danger.btn-block{"data-confirm" => "Are you sure?", "data-method" => "delete", :href => app_path(@app), :rel => "nofollow"} Destroy

app/views/apps/index.html.haml
.menu-notify
  .profile-left  
  .Profile-mid
    %h5.pro-link Aplicaciones
  .clearfix
.details-grid
  = render partial: "app", collection: @apps

app/views/apps/new.html.haml
#admin-view
  .headding-notify
    .headding-left
      = link_to apps_path do
        %h5.pro-link
          %i.fa.fa-chevron-left
    .headding-mid
      %h5.pro-link Nueva App
    .clearfix
  .shade
    .container
      .col-md-12.col-sm-12
        = render 'new_form'

app/views/apps/show.html.haml
.body-back
  .phone-box.wrap.push
    .menu-notify
      .profile-left
        %a{:href => root_path}
          %i.fa.fa-chevron-left
      .Profile-mid
        %h5.pro-link Aplicaciones
      .clearfix
    .details-grid
      .details-shade
        .col-md-6.details-left
          %img.img-circle.border-effect{:alt => " ", :src => @app.avatar(:thumb)}/
        .col-md-6.details-right
          %h3=@app.name
          %h4 Imprescindibles
          %a.btn.btn-info{:href => @app.download_url, target: "_blank"} Descargar
          - if current_user.is_admin?
            %a.btn.btn-warning{:href => edit_app_path(@app), target: "_blank"} Editar
          .clearfix
        .clearfix
    .col-md-12.app-info-open
      %h3 Descripción
      = @app.description.html_safe
      .clearfix
    .clearfix